
apiVersion: v1
kind: Service
metadata:
  name: app-lanchonete-service
spec:
  type: NodePort
  selector:
    app: app-lanchonete-deployment
  ports:
    - port: 80
      nodePort: 32001 
      targetPort: 3000
