
apiVersion: v1
kind: Service
metadata:
  name: app-lanchonete-service
spec:
  selector:
    app: app-lanchonete-deployment
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
  type: LoadBalancer

